# -*- coding: utf-8 -*-
"""The_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xoNBMxSDoJJ68OOOSC7UsnLHaPIeLij

# Automated Customer Complaint Analyzer (LLM-Based)

### Task 1 - Set up the project environment
"""

# - openai: used to connect to OpenAI's API (we will use it later to fine-tune and run the model)
# - python-dotenv: helps us safely load our API key from a .env file instead of writing it directly in code
!pip install openai python-dotenv

!pip install --upgrade openai

"""Importing modules"""

# Import required libraries for the project

import pandas as pd          # Used to load and work with the dataset (customer complaints in table format)

import os, time             # os: helps access environment variables (like API keys)
                            # time: used for adding delays or tracking execution time if needed

from openai import OpenAI   # Main library to interact with OpenAI API (for fine-tuning and model usage)

from dotenv import load_dotenv  # Loads API keys from a .env file into the environment (secure way to manage secrets)

import json                 # Used to read/write data in JSON format (required for training data and API responses)

import matplotlib.pyplot as plt  # Used for visualizing results (e.g., model performance, score distribution)

print("Modules are imported.")

"""Setting up the OpenAI API:

* Prepare a .env file to store the OpenAI API key.
* Uploading the .env file to our colab environment
* Load the API key and setup the API
"""

load_dotenv('apikey.env.txt')
APIKEY = os.getenv('MY_API_KEY')

"""Creating OpenAI Client"""

# Step: Create OpenAI client
# The "client" is an object that connects our code to OpenAI's API.
# We pass our API key so OpenAI knows who is making the request.

# What is happening here:
# - OpenAI() creates a client instance (like setting up a connection)
# - This client will be used later to:
#     • send training data for fine-tuning
#     • generate responses from the model
#     • interact with OpenAI services
# Client is called API handler
client = OpenAI(
  api_key = APIKEY
)
client

"""### Task 2 - Prepare the training data

Loading the provided `Customer Complaints.csv`
"""

"""
Each row contains:
  Complaints → raw text (input)
  Details → structured output (target / correct extracted information)
"""
training_data = pd.read_csv('Customer Complaints.csv')
training_data #This dataset is labeled

"""OpenAI fine-tuning does NOT accept CSV directly.
It expects data in a chat format (JSONL) like.
Because GPT models are trained as chat systems, not simple input-output models. Each role has a purpose:

system → tells the model what task to do
user → provides the input (complaint)
assistant → provides the correct answer (expected output)

**Converting the Complaints records to json**

To be able to use the data for the fine-tuning purpose, we first need to convert each row of the dataframe into the following format:

<pre>
<code>
{
  <span style="color: blue;">"messages"</span>: [
    {
      <span style="color: blue;">"role"</span>: <span style="color: red;">"system"</span>,
      <span style="color: blue;">"content"</span>: "<span style="color: green;">Providing context about the user's prompt.
                  It may include information about the task,
                  instructions, or background details relevant
                  to the conversation.</span>"
    },
    {
      <span style="color: blue;">"role"</span>: <span style="color: red;">"user"</span>,
      <span style="color: blue;">"content"</span>: "<span style="color: green;">the prompt or input provided by the user,
                  which typically initiates the conversation with the assistant.</span>"
    },
    {
      <span style="color: blue;">"role"</span>: <span style="color: red;">"assistant"</span>,
      <span style="color: blue;">"content"</span>: "<span style="color: green;">The desired response or output generated by
                  the assistant in response to the user's prompt.</span>"
    }
  ]
}
</code>
</pre>

Let's get started!

Let's define a method that get's a row of the dataframe and convert it into the json format
"""

def save_as_json(row): # This function converts one row → one training example

  system_content = """
      Given a customer complaint text, extract and return the following information in json (dict) format:
      - Topic: The product/department that the customer has a complaint about.
      - Problem: A two or three-word description of what exactly the problem is.
      - Customer_Dissatisfaction_Index: is a number between 0 and 100 showing
             how angry the customer is about the problem.
  """
  # one trining sample
  formatted_data = {
        "messages": [
            {"role": "system", "content": system_content}, # training instructions
            {"role": "user", "content": row.Complaints},  # training complaint text
            {"role": "assistant", "content": row.Details} # training correct structured answer
        ]
      }

  with open("training_data.json", "a") as json_file:
        json.dump(formatted_data, json_file)
        json_file.write("\n")

"""Now let's use of this method to generate the `training_data.json`"""

for idx, row in training_data.iterrows():
  save_as_json(row)

"""### Task 3 - Fine-tune GPT 3.5 based on our training data

Let's import the json file we prepared as our training data

Before fine-tuning, OpenAI needs your dataset:

Uploaded,
Validated,
Stored internally.
"""

# 🔷 client.files.create(...) — Notes

# Purpose:
# Upload a file to OpenAI so it can be used later (e.g., for fine-tuning)

# What it does:
# - Takes a local file
# - Sends it to OpenAI servers via API
# - Stores and validates the file

# Input:
# - file → opened in binary mode (e.g., open('file.json', 'rb'))
# - purpose → tells how the file will be used ('fine-tune')

# Output:
# - Returns a FileObject with:
#     • id (used later for training)
#     • status ('uploaded' / 'processed')

# Key point:
# This step only uploads the data — it does NOT start training

data_file = client.files.create(
    file = open('training_data.json', 'rb'),
    purpose = 'fine-tune'
)
data_file

"""Create the Fine Tuning Job"""

# This step starts the fine-tuning job on OpenAI servers
# The model is not ready yet — it is currently being trained

# status='validating_files' means:
# OpenAI is checking if the dataset format is correct

# After this, training will begin automatically

# We can use the job ID to track progress

fine_tuning_job = client.fine_tuning.jobs.create(
    training_file=data_file.id,
    model='gpt-3.5-turbo',
    hyperparameters={
        'n_epochs': 1
    }
)

fine_tuning_job

"""Let's retrieve the state of the fine-tune"""

# Check the current status of the fine-tuning job
# This helps us know whether training is still running or completed

# retrieve() gets the latest job info using the job ID
# status tells us the current stage (validating, running, succeeded, etc.)

retrieved_job = client.fine_tuning.jobs.retrieve(fine_tuning_job.id)
status = retrieved_job.status
print(status)

"""### Task 4 - Evaluate model

Let's retrieve the event messages to check out the learning process of our fine-tuning job.
"""

events = list(client.fine_tuning.jobs.list_events(fine_tuning_job_id=retrieved_job.id, limit=100).data)
events

for e in events:
  print(e.message)

for e in events:
  print(e.data)

"""Let's extract the training loss in each learning step"""

steps = []
train_loss = []

for e in events:
    if e.data:
        step = e.data.get('step')
        loss = e.data.get('train_loss')

        if step is not None and loss is not None:
            steps.append(step)
            train_loss.append(loss)

print(steps)
print(train_loss)

"""Use a line chart to visualize the train_loss in each step"""

plt.plot(steps, train_loss, marker = 'o', linestyle='-')

"""### Task 5 - Deploy our model

Let's take a look at `retrieved_job` again
"""

myLLM = retrieved_job.fine_tuned_model
print(myLLM)

"""Defining a method to extract information from a given user complaint using a specific LLM and return the results."""

def extract_details(user_complaint, model_name):
    """
    This function extracts information from a given user complaint using a specific LLM (Large Language Model).

    Parameters:
    user_complaint (str): The text of the user's complaint.
    model_name (str): The name of the specific LLM model to use for extraction.
    """

    system_content = """
        Given a customer complaint text, extract and return the following information in JSON (dict) format:
        - Topic
        - Problem
        - Customer_Dissatisfaction_Index
    """

    # Generate a response using the specified model and the user's complaint
    response = client.chat.completions.create(
        model = model_name,
        messages=[
            {"role": "system", "content": system_content},  # System content explaining the expected output
            {"role": "user", "content": user_complaint}  # User's complaint passed as content
        ]
    )

    # Return the content of the generated response
    return response.choices[0].message.content

"""Let's use our fine-tuned model to extract the details for the following user complaint:

*TV channels keep disappearing from my subscription! What's going on? Extremely annoyed with this service!*
"""

complaint = "TV channels keep disappearing from my subscription! what's going on? Extremely annoyed with this service!"
extract_details(complaint, myLLM)

"""Let's test our `GPT-4` model with the same user complaint"""



complaint = "TV channels keep disappearing from my subscription! what's going on? Extremely annoyed with this service!"
extract_details(complaint, 'gpt-4')

"""Let's try for the following complaint:

*Line is down! It is really annoying!*
"""

complaint = "Line is down! It is really annoying!"
extract_details(complaint, myLLM)

"""Now let's compare the results from GPT-4"""

complaint = "Line is down! It is really annoying!"
extract_details(complaint, 'gpt-4')

"""We can see that our model, which is trained on our dataset, provides better answers compared to GPT-4. Our model is fine-tuned based on our data and is familiar with the different edge cases and the context of our dataset."""

customer_complaint = "I am very Angry! I want my money back!"
extract_details(complaint, myLLM)

